### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by rmullettt** [Microsoft/vsts-agent-cookbook#16]
Using Chef 12.14.89 I get the following error when it is trying to authenticate to VSTS:

 Chef::Exceptions::ValidationFailed: Required argument :principals is missing!

Any help on resolving this would be greatly appreciated.

vsts_agent 'agent_02' do
  install_dir dir
  vsts_url 'https:/my_company.visualstudio.com'
  vsts_pool 'default'
  vsts_token 'my_PAT'
  windowslogonaccount 'corp\User' # will be used only on windows
  windowslogonpassword 'my_password' # will be used only on windows
  action :install
end

Thanks!!!

**Comment by ivadim** [comment]
Hi @rmullettt , 
could you please send a log from chef run? I don't think it is trying to auth against VSTS as error looks refer to the parameter validation. 
P.s. Don't forget to clean all sensitive information from logs.

**Comment by rmullettt** [comment]
Here is the log from the chef client run.  please let me know if you need anything else.

Thanks!!

Starting Chef Client, version 12.19.36
[2017-06-28T16:08:11-04:00] INFO: *** Chef 12.19.36 ***
[2017-06-28T16:08:11-04:00] INFO: Platform: x64-mingw32
[2017-06-28T16:08:11-04:00] INFO: Chef-client pid: 4988
[2017-06-28T16:08:18-04:00] INFO: Run List is [recipe[seven_zip], recipe[unf_vsts_build_agent]]
[2017-06-28T16:08:18-04:00] INFO: Run List expands to [seven_zip, unf_vsts_build_agent]
[2017-06-28T16:08:18-04:00] INFO: Starting Chef Run for appprd02vsbuild.corp.unifirst.com
[2017-06-28T16:08:18-04:00] INFO: Running start handlers
[2017-06-28T16:08:18-04:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["seven_zip", "unf_vsts_build_agent"]
[2017-06-28T16:08:18-04:00] INFO: Loading cookbooks [homebrew@2.1.2, mingw@1.2.4, seven_zip@2.0.2, ohai@4.2.3, build-ess
ential@7.0.2, compat_resource@12.16.3, windows@3.1.0, unf_vsts_build_agent@0.1.0, ark@3.1.0, vsts_agent@1.3.1]
Synchronizing Cookbooks:
  - homebrew (2.1.2)
  - mingw (1.2.4)
  - seven_zip (2.0.2)
  - ohai (4.2.3)
  - build-essential (7.0.2)
  - compat_resource (12.16.3)
  - windows (3.1.0)
  - ark (3.1.0)
  - vsts_agent (1.3.1)
[2017-06-28T16:08:19-04:00] INFO: Storing updated cookbooks/unf_vsts_build_agent/recipes/default.rb in the cache.
  - unf_vsts_build_agent (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: seven_zip::default
  * windows_package[7-Zip 15.14 (x64 edition)] action install[2017-06-28T16:08:19-04:00] INFO: Processing windows_packag
e[7-Zip 15.14 (x64 edition)] action install (seven_zip::default line 21)

  Recipe: <Dynamically Defined Resource>
    * remote_file[c:\chef\cache\package\7z1514-x64.msi] action create[2017-06-28T16:08:19-04:00] INFO: Processing remote
_file[c:\chef\cache\package\7z1514-x64.msi] action create (dynamically defined)
 (up to date)
     (up to date)
Recipe: unf_vsts_build_agent::default
  * vsts_agent[agent_02] action install[2017-06-28T16:08:19-04:00] INFO: Processing vsts_agent[agent_02] action install
(unf_vsts_build_agent::default line 15)


    ================================================================================
    Error executing action `install` on resource 'vsts_agent[agent_02]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Required argument :principals is missing!

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/vsts_agent/providers/default.rb:64:in `block (3 levels) in class_from_file'
    c:/chef/cache/cookbooks/vsts_agent/providers/default.rb:62:in `block (2 levels) in class_from_file'
    c:/chef/cache/cookbooks/vsts_agent/providers/default.rb:40:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/unf_vsts_build_agent/recipes/default.rb

     15: vsts_agent 'agent_02' do
     16:   install_dir dir
     17:   vsts_url 'https://mycompany.visualstudio.com'
     18:   vsts_pool 'default'
     19:   vsts_token 'myPAT'
     20:   windowslogonaccount 'corp\myUser' # will be used only on windows
     21:   windowslogonpassword 'myPassword' # will be used only on windows
     22:   action :install
     23: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/unf_vsts_build_agent/recipes/default.rb:15:in `from_file'

    vsts_agent("agent_02") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :vsts_agent
      cookbook_name "unf_vsts_build_agent"
      recipe_name "default"
      install_dir "D:\\agents"
      vsts_url "https://myCompany.visualstudio.com"
      vsts_pool "default"
      vsts_token "myPAT"
      windowslogonaccount "corp\\myUser"
      windowslogonpassword "myPOassword"
      agent_name "agent_02"
      vsts_auth "PAT"
      work_folder "_work"
      env {}
    end

    Platform:
    ---------
    x64-mingw32

[2017-06-28T16:08:20-04:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-06-28T16:08:20-04:00] ERROR: Running exception handlers
Running handlers complete
[2017-06-28T16:08:20-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2017-06-28T16:08:20-04:00] INFO: Sending resource update report (run-id: 2136ec3c-5eec-47d8-90f0-b0b00895749d)
[2017-06-28T16:08:20-04:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2017-06-28T16:08:20-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-06-28T16:08:20-04:00] FATAL: Chef::Exceptions::ValidationFailed: vsts_agent[agent_02] (unf_vsts_build_agent::defau
lt line 15) had an error: Chef::Exceptions::ValidationFailed: Required argument :principals is missing!

**Comment by ivadim** [comment]
@rmullettt please try to add an `user` attribute to the resource. It is used to set an owner of the files and directories. In your case it will be "corp\myUser".
