### ISSUE TITLE
On-Prem compatibility?

### ISSUE THREAD

**Issue by lavahot** [Microsoft/vsts-agent-cookbook#17]
Any plans to accomodate On-Premises rollouts?

**Comment by lavahot** [comment]
Seems like this would be pretty easy if the regex for the URI was changed to accept TFS URLs as well. Or even match against an OR of two different regexs.

**Comment by ivadim** [comment]
Hi @lavahot. I will try to implement this at the weekend

**Comment by ivadim** [comment]
@lavahot could you please validate the latest cookbook version (2.0.0)?. I removed strict check for visualstudio.com
