### ISSUE TITLE
Default agent version?

### ISSUE THREAD

**Issue by lavahot** [Microsoft/vsts-agent-cookbook#19]
Should the default agent be the latest pre-release: 2.125.1, or the latest release: 2.124.0?

**Comment by ivadim** [comment]
In preview they started to use .net core 2.0 which unblocks Debian Stretch, so I decided to use it. But it's a good point. Now it's not possible to rollback to the previous version as download URL were changed. I will add support back.

@lavahot  do you have any problems with pre-release version?

**Comment by lavahot** [comment]
I haven't yet used the pre-release version, so I technically have not had any problems, but I plan on deploying into production which means that I will probably wind up using the release version anyway. I'm going to hold back and use the v1 of the cookbook for the moment anyway, so not a big rush.

**Comment by ivadim** [comment]
Actually, you can easily overwrite behavior by changing default attributes.
In your wrapper cookbook add
```
default['vsts_agent']['binary']['version'] = '2.124.0'
case node['platform_family']
when 'windows'
  default['vsts_agent']['binary']['url'] = 'https://github.com/Microsoft/vsts-agent/releases/download/v%s/vsts-agent-win7-x64-%s.zip'
when 'debian'
  default['vsts_agent']['binary']['url'] =
    if platform?('ubuntu') && node['platform_version'].to_i >= 16
      'https://github.com/Microsoft/vsts-agent/releases/download/v%s/vsts-agent-ubuntu.16.04-x64-%s.tar.gz'
    else
      'https://github.com/Microsoft/vsts-agent/releases/download/v%s/vsts-agent-ubuntu.14.04-x64-%s.tar.gz'
    end
when 'mac_os_x', 'mac_os_x_server'
  default['vsts_agent']['binary']['url'] = 'https://github.com/Microsoft/vsts-agent/releases/download/v%s/vsts-agent-osx.10.11-x64-%s.tar.gz'
end
``` 
You can remove platforms what you don't need.

**Comment by lavahot** [comment]
Hmm. Okay, I'll give it a shot.

**Comment by ivadim** [comment]
Hi @lavahot , 
Did you try a new cookbook and these changes?

**Comment by lavahot** [comment]
Sorry, I spent all day tracking down a bug. Looks like it had something to do with the v1 cookbook itself (I don't know what exactly), so I'm gonna spin up v2 right now and let you know.

**Comment by lavahot** [comment]
Good news and bad news: 2.126.0 has been properly released, bad news is they totally changed the URL for it.

**Comment by ivadim** [comment]
@lavahot  I updated cookbook with a new version and new urls
