### ISSUE TITLE
Pinning of seven_zip dependency using ~> prevents users from selecting version 3.0.0

### ISSUE THREAD

**Issue by estenrye** [Microsoft/vsts-agent-cookbook#25]
The current seven_zip dependency declaration is impacting our ability to use the most current version of the seven_zip cookbook.

Consider using `>= 2.0.0` instead of `~> 2.0.0`

**Comment by ivadim** [comment]
Hi @estenrye,
Thank you for reporting this issue. I fixed it in version v2.0.3
