### ISSUE TITLE
Feature Request: Add support for deployment groups

### ISSUE THREAD

**Issue by estenrye** [Microsoft/vsts-agent-cookbook#27]
I have a  team at work that is using the new TFS Deployment groups.  Is it possible support for this feature could be added to the cookbook.  Below is an example configuration from the config.cmd:

`.\config.cmd --deploymentgroup --deploymentgroupname "test group" --agent $env:COMPUTERNAME --runasservice --work '_work' --url 'https://tfs.example.com/tfs/' --collectionname 'DefaultCollection' --projectname 'Example Company'`

**Comment by ivadim** [comment]
Hi @estenrye, I implemented deployment groups support in #31 . Please test release v3.0.0

**Comment by ivadim** [comment]
Usage:
```
vsts_agent 'deployment_agent_01' do
  install_dir dir
  deploymentGroup true
  deploymentGroupName 'project1-deployment-group'
  projectName 'project1'
  collectionName 'DefaultCollection'
  deploymentGroupTags "web, db"
  user 'vagrant'
  group 'vagrant'
  path '/usr/local/bin/:/usr/bin:/opt/bin/' # only works on nix systems
  env('M2_HOME' => '/opt/maven', 'JAVA_HOME' => '/opt/java') # only works on nix systems
  vsts_url 'https://contoso.visualstudio.com'
  vsts_token 'my_secret_token_from_vsts'
  windowslogonaccount 'builder' # will be used only on windows
  windowslogonpassword 'Pas$w0r_d' # will be used only on windows
  action :install
end
```

**Comment by estenrye** [comment]
Hi @ivadim, I won't be able to test this this sprint, but I will talk with my scrum master about getting it on the backlog for an upcoming sprint.

**Comment by estenrye** [comment]
Thanks for your quick action on this feature request.
